pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - main
skip_tags: true
configuration: Release
image: Visual Studio 2019

install:
- ps: (new-object Net.WebClient).DownloadString("https://raw.github.com/madskristensen/ExtensionScripts/master/AppVeyor/vsix.ps1") | iex

before_build:
- cmd: nuget restore .\VSIX\RapidXamlToolkit.sln -Verbosity quiet
- ps: Vsix-IncrementVsixVersion | Vsix-UpdateBuildVersion
  #- ps: Vsix-TokenReplacement src\source.extension.cs 'Version = "([0-9\\.]+)"' 'Version = "{version}"'

build_script:
  - msbuild .\VSIX\RapidXamlToolkit.sln /p:configuration=Release /p:DeployExtension=false /p:ZipPackageCompressionLevel=normal /v:n

after_test:
  - ps: Vsix-PushArtifacts | Vsix-PublishToGallery
  
skip_commits:
  files:
    - _build/*
    - Assets/*
    - docs/*
    - '**/*.md'
